[package]
name = "ydb-ng-bridge"
version = "0.1.0"
authors = ["Charles Hathaway <chathaway@logrit.com>"]
edition = "2018"

[dependencies]

[build-dependencies]
bindgen = "0.42.2"
pkg-config = "0.3.14"
